spring:
  config:
    import: configserver:,configtree:/workspace/secrets/*/
    cloud:
      config:
        fail-fast: true
  datasource:
    url: jdbc:postgresql://polar-server.postgres.database.azure.com:5432/polardb_catalog
  rabbitmq:
    host: polar-rabbitmq.rabbitmq-system.svc.cluster.local
    port: 5672
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://86a976e43cff49d18ff7.eastus.aksapp.io/auth/realms/PolarBookshop

