apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/baronnoraz/catalog-service/k8s?ref=v0.0.1

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  name: catalog-service
  files:
  - application-prod.yml

images:
- name: catalog-service
  newName: ghcr.io/baronnoraz/catalog-service
  newTag: 0.0.1

replicas:
- count: 2
  name: catalog-service
