apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/baronnoraz/config-service/k8s?ref=v0.0.1

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: config-service

images:
- name: config-service
  newName: ghcr.io/baronnoraz/config-service
  newTag: 0.0.2

replicas:
- count: 1
  name: config-service
